add_requires("luajit 2.1.0-beta3")
add_requires("brotli 1.0.9")
add_requires("expat 2.2.10")
add_requires("cryptopp")

includes("scripts/lsquic.lua")
includes("scripts/udns.lua")
includes("scripts/ip2loc.lua")
includes("scripts/injection.lua")
includes("scripts/maxminddb.lua")
includes("scripts/bcrypt.lua")
includes("scripts/openlitespeed.lua")