target("ip2loc")
    set_kind("static")
    set_configdir("../src/ip2loc")
    add_configfiles("../config/ip2loc_config.h.in", {filename = "config.h"})
    add_includedirs("../src/ip2loc/libIP2Location", {public=true})
    add_files("../src/ip2loc/libIP2Location/*.c")
    set_configvar("PKG_VER", "8.4.0")

    -- before_build(function(target)
    --     os.cd("src/ip2loc")
    --     ver = os.iorun("git describe --tags")
    --     ver = string.gsub( ver,"\r", "" )
    --     ver = string.gsub( ver,"\n", "" )
    --     target:set_configvar("PKG_VER", ver)
    --     os.cd("../../")
    -- end)