includes("boringssl.lua")
add_requires("xxhash")

target("lsquic")
	set_kind("static")
    add_deps("boringssl")
    add_packages("xxhash")
    add_includedirs("../src/lsquic/include", {public=true})
    add_includedirs("../src/lsquic/src/liblsquic")
    add_includedirs("../src/lsquic/src/liblsquic/ls-qpack")
    add_includedirs("../src/lsquic/src/lshpack")
    add_files("../src/lsquic/src/liblsquic/*.c|common_*.c")
    add_files("../src/lsquic/src/liblsquic/ls-qpack/*.c")
    add_files("../src/lsquic/src/lshpack/*.c")
    add_defines("XXH_HEADER_NAME=\"xxhash.h\"")
