target("ols_lsr")
    set_kind("static")
    add_includedirs("../src/ols/include", {public=true})
    add_includedirs("../src/ols/src", {public=true})
    add_includedirs("../src/ols/src/lsr", {public=true})
    add_files("../src/ols/src/lsr/*.cpp")

target("ols_util")
    set_kind("static")
    add_deps("ols_lsr")
    -- add_includedirs("../src/ols/include")
    -- add_includedirs("../src/ols/src")
    add_includedirs("../src/ols/src/util", {public=true})
    add_includedirs("../src/ols/src/util/misc")
    add_includedirs("../src/ols/src/util/sysinfo")
    add_files("../src/ols/src/util/*.cpp|logfile.cpp|timer.cpp")
    add_files("../src/ols/src/util/misc/profiletime.cpp")
    add_files("../src/ols/src/util/sysinfo/partitioninfo.cpp")
    add_files("../src/ols/src/util/sysinfo/nicdetect.cpp")
    add_files("../src/ols/src/util/sysinfo/systeminfo.cpp")
    add_defines("OPENSSL_IS_BORINGSSL=1")
    add_defines("USE_BROTLI=1")


target("ols_edio")
    set_kind("static")
    add_deps("ols_util")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src/edio", {public=true})
    add_files("../src/ols/src/edio/*.cpp|callbackqueue.cpp");

target("ols_adns")
    set_kind("static")
    add_deps("ols_edio");
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src/adns", {public=true})
    add_files("../src/ols/src/adns/*.cpp");

target("ols_h2")
    set_kind("static")
    add_deps("ols_edio", "lsquic")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src/h2", {public=true})
    add_files("../src/ols/src/h2/*.cpp|ssledstream.cpp");

target("ols_http")
    set_kind("static")
    add_deps("ols_util", "lsquic", "maxminddb", "bcrypt")
    add_packages("brotli")
    add_defines("ENABLE_IPTOGEO2=1")
    add_defines("PACKAGE_VERSION=\"1.7.14\"")
    add_defines("LS_MODULE_VERSION_INFO=\"Unknown\"")
    add_defines("DEFAULT_TMP_DIR=\"/tmp\"")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src/http", {public=true})
    add_files("../src/ols/src/http/*.cpp");

target("ols_log4cxx")
    set_kind("static")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src")
    add_includedirs("../src/ols/src/log4cxx", {public=true})
    add_files("../src/ols/src/log4cxx/**.cpp")

target("ols_lsapi")
    set_kind("static")
    add_deps("lsquic")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src")
    add_includedirs("../src/ols/src/lsiapi", {public=true})
    add_files("../src/ols/src/lsiapi/**.cpp")
    add_defines("PACKAGE_VERSION=\"1.7.14\"")

target("ols_quic")
    set_kind("static")
    add_deps("lsquic")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src")
    add_includedirs("../src/ols/src/quic", {public=true})
    add_files("../src/ols/src/quic/**.cpp")

target("ols_shm")
    set_kind("static")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src")
    add_includedirs("../src/ols/src/shm", {public=true})
    add_files("../src/ols/src/shm/**.cpp|ls_shmhashcmp.cpp")

target("ols_socket")
    set_kind("static")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src")
    add_includedirs("../src/ols/src/socket", {public=true})
    add_files("../src/ols/src/socket/**.cpp")
    add_cxxflags("-fpermissive")

target("ols_spdy")
    set_kind("static")
    add_deps("lsquic")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src")
    add_includedirs("../src/ols/src/spdy", {public=true})
    add_files("../src/ols/src/spdy/**.cpp")

target("ols_ssi")
    set_kind("static")
    add_deps("lsquic")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src")
    add_includedirs("../src/ols/src/ssi", {public=true})
    add_files("../src/ols/src/ssi/**.cpp")

target("ols_sslpp")
    set_kind("static")
    add_deps("ols_util")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src")
    add_includedirs("../src/ols/src/sslpp", {public=true})
    add_includedirs("../src/ols/src/sslpp/ocsp")
    add_files("../src/ols/src/sslpp/**.cpp")
    add_files("../src/ols/src/sslpp/ocsp/ocsp.c")

    add_defines("OPENSSL_IS_BORINGSSL=1")
    add_defines("USE_BROTLI=1")
    add_includedirs("../src/boringssl/include")
    add_files("../src/boringssl/build/crypto/libcrypto.a")
    add_files("../src/boringssl/build/decrepit/libdecrepit.a")
    
target("ols_thread")
    set_kind("static")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src")
    add_includedirs("../src/ols/src/thread", {public=true})
    add_files("../src/ols/src/thread/**.cpp")

target("ols_ext_cgi")
    set_kind("static")
    add_deps("lsquic", "ols_log4cxx", "ols_http")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src")
    add_includedirs("../src/ols/src/extensions/cgi", {public=true})
    add_files("../src/ols/src/extensions/cgi/**.cpp|cgiconnection.cpp")

target("ols_ext_fcgi")
    set_kind("static")
    add_deps("lsquic", "ols_log4cxx", "ols_http")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src")
    add_includedirs("../src/ols/src/extensions/fcgi", {public=true})
    add_files("../src/ols/src/extensions/fcgi/**.cpp|sample*.cpp|fcgistarter.cpp|fcgirequest.cpp")

target("ols_ext_jk")
    set_kind("static")
    add_deps("lsquic", "ols_log4cxx", "ols_http")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src")
    add_includedirs("../src/ols/src/extensions/jk", {public=true})
    add_files("../src/ols/src/extensions/jk/**.cpp")

target("ols_ext_lsapi")
    set_kind("static")
    add_deps("lsquic", "ols_log4cxx", "ols_http")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src")
    add_includedirs("../src/ols/src/extensions/lsapi", {public=true})
    add_files("../src/ols/src/extensions/lsapi/**.cpp")

target("ols_ext_proxy")
    set_kind("static")
    add_deps("lsquic", "ols_log4cxx", "ols_http")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src")
    add_includedirs("../src/ols/src/extensions/proxy", {public=true})
    add_files("../src/ols/src/extensions/proxy/**.cpp")

target("ols_ext_registry")
    set_kind("static")
    add_deps("lsquic", "ols_log4cxx", "ols_http")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src")
    add_includedirs("../src/ols/src/extensions/registry", {public=true})
    add_files("../src/ols/src/extensions/registry/**.cpp")

target("ols_ext")
    set_kind("static")
    add_deps("lsquic", "ols_log4cxx", "ols_http")
    add_deps("ols_ext_cgi", "ols_ext_fcgi", "ols_ext_jk")
    add_deps("ols_ext_lsapi", "ols_ext_proxy", "ols_ext_registry")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src")
    add_includedirs("../src/ols/src/extensions", {public=true})
    add_files("../src/ols/src/extensions/*.cpp")

target("ols_mod_modsec")
    set_kind("shared")
    add_includedirs("../src/mod_sec/headers")
    add_includedirs("../src/ols/include")
    add_includedirs("../src/ols/src")
    add_files("../src/mod_sec/src/.libs/libmodsecurity.a")
    add_files("../src/ols/src/modules/modsecurity-ls/*.cpp")

-- target("openlitespeed")
--     set_kind("binary")
--     add_deps("boringssl", "lsquic", "maxminddb", "ip2loc", "injection", "udns")
--     add_packages("brotli", "luajit", "expat")
--     add_includedirs("../src/ols/include")
--     add_includedirs("../src/ols/src")
    -- on_load(function(target)
    --     -- ols module includedir
    --     for _, dir in ipairs(os.dirs("../src/ols/src/*")) do
    --         target:add('includedirs', dir)
    --     end
    -- end)

    -- add_files("../src/ols/src/**.c")
    -- add_files("../src/ols/src/**.cpp")
