add_defines("USE_BROTLI=1")
add_defines("ENABLE_IPTOGEO2=1")

add_defines("OPENSSL_IS_BORINGSSL=1")
add_defines("PACKAGE_VERSION=\"1.7.14\"")
add_defines("LS_MODULE_VERSION_INFO=\"Unknown\"")

add_defines("SERVERROOT=\"/usr/local/lsws\"")
add_defines("OPENLSWS_USER=\"nobody\"")
add_defines("OPENLSWS_GROUP=\"nobody\"")
add_defines("OPENLSWS_ADMIN=\"admin\"")
add_defines("OPENLSWS_EMAIL=\"root@localhost\"")
add_defines("OPENLSWS_ADMINSSL=\"yes\"")
add_defines("OPENLSWS_ADMINPORT=7080")
add_defines("USE_LSPHP7=\"yes\"")
add_defines("DEFAULT_TMP_DIR=\"/tmp/lshttpd\"")
add_defines("PID_FILE=\"/tmp/lshttpd/lshttpd.pid\"")
add_ldflags("-lrt")
add_ldflags("-lcrypt")
add_packages("zlib", {system=false})

target("ols_base")
    set_kind("phony")
    add_includedirs("../src/ols/include", {public=true})
    add_includedirs("../src/ols/src", {public=true})
    add_files("../src/boringssl/build/ssl/libssl.a")
    add_files("../src/boringssl/build/crypto/libcrypto.a")
    add_files("../src/boringssl/build/decrepit/libdecrepit.a")
    

target("ols_lsr")
    set_kind("static")
    add_deps("ols_base")
    add_includedirs("../src/ols/src/lsr", {public=true})
    add_files("../src/ols/src/lsr/*.cpp")
    add_files("../src/ols/src/lsr/*.c")

target("ols_util")
    set_kind("static")
    add_packages("expat", "brotli")
    add_deps("ols_base", "ols_lsr", "ols_edio")
    add_includedirs("../src/ols/src/util", {public=true})
    add_includedirs("../src/ols/src/util/misc", {public=true})
    add_includedirs("../src/ols/src/util/sysinfo", {public=true})
    add_files("../src/ols/src/util/*.cpp|logfile.cpp|timer.cpp")
    add_files("../src/ols/src/util/*.c")
    add_files("../src/ols/src/util/misc/profiletime.cpp")
    add_files("../src/ols/src/util/sysinfo/partitioninfo.cpp")
    add_files("../src/ols/src/util/sysinfo/nicdetect.cpp")
    add_files("../src/ols/src/util/sysinfo/systeminfo.cpp")
    -- add_defines("OPENSSL_IS_BORINGSSL=1")
    -- add_defines("USE_BROTLI=1")

target("ols_edio")
    set_kind("static")
    add_deps("ols_base")
    add_includedirs("../src/ols/src/edio", {public=true})
    add_files("../src/ols/src/edio/*.cpp|callbackqueue.cpp")

target("ols_adns")
    set_kind("static")
    add_deps("udns")
    add_deps("ols_base","ols_edio")
    add_includedirs("../src/ols/src/adns", {public=true})
    add_files("../src/ols/src/adns/*.cpp");

target("ols_h2")
    set_kind("static")
    add_deps("ols_base", "ols_edio", "lsquic")
    add_includedirs("../src/ols/src/h2", {public=true})
    add_files("../src/ols/src/h2/*.cpp|ssledstream.cpp");

target("ols_http")
    set_kind("static")
    add_deps("lsquic", "maxminddb", "bcrypt")
    add_deps("ols_base", "ols_util", "ols_ssi", "ols_mod_gzip", "ols_edio")
    add_deps("ols_log4cxx", "ols_ext", "ols_spdy")
    add_packages("brotli", "pcre", "zlib")
    add_includedirs("../src/ols/src/http", {public=true})
    add_files("../src/ols/src/http/*.cpp");

target("ols_log4cxx")
    set_kind("static")
    add_deps("ols_base")
    add_includedirs("../src/ols/src/log4cxx", {public=true})
    add_files("../src/ols/src/log4cxx/**.cpp")

target("ols_lsapi")
    set_kind("static")
    add_deps("ols_base", "lsquic", "ols_mod")
    add_includedirs("../src/ols/src/lsiapi", {public=true})
    add_files("../src/ols/src/lsiapi/**.cpp")

target("ols_quic")
    set_kind("static")
    add_deps("ols_base", "lsquic", "ols_socket")
    add_includedirs("../src/ols/src/quic", {public=true})
    add_files("../src/ols/src/quic/**.cpp")

target("ols_shm")
    set_kind("static")
    add_deps("ols_base")
    add_includedirs("../src/ols/src/shm", {public=true})
    add_files("../src/ols/src/shm/**.cpp|ls_shmhashcmp.cpp")

target("ols_socket")
    set_kind("static")
    add_deps("ols_base")
    add_includedirs("../src/ols/src/socket", {public=true})
    add_files("../src/ols/src/socket/**.cpp")
    add_cxxflags("-fpermissive", {force=true})

target("ols_spdy")
    set_kind("static")
    add_deps("ols_base", "lsquic")
    -- add_packages("zlib")
    add_includedirs("../src/ols/src/spdy", {public=true})
    add_files("../src/ols/src/spdy/**.cpp")

target("ols_ssi")
    set_kind("static")
    add_deps("ols_base", "lsquic")
    add_includedirs("../src/ols/src/ssi", {public=true})
    add_files("../src/ols/src/ssi/**.cpp")

target("ols_sslpp")
    set_kind("static")
    add_deps("ols_base", "ols_util", "ols_lsr", "ols_thread")
    add_includedirs("../src/ols/src/sslpp", {public=true})
    add_includedirs("../src/boringssl/include", {public=true})
    add_includedirs("../src/ols/src/sslpp/ocsp")
    add_files("../src/ols/src/sslpp/**.cpp")
    add_files("../src/ols/src/sslpp/*.c")
    add_files("../src/ols/src/sslpp/ocsp/ocsp.c")
    add_files("../src/boringssl/build/ssl/libssl.a")
    add_files("../src/boringssl/build/crypto/libcrypto.a")
    add_files("../src/boringssl/build/decrepit/libdecrepit.a")
    
target("ols_thread")
    set_kind("static")
    add_deps("ols_base")
    add_includedirs("../src/ols/src/thread", {public=true})
    add_files("../src/ols/src/thread/**.cpp")

target("ols_ext")
    set_kind("static")
    add_deps("ols_base")
    add_includedirs("../src/ols/src/extensions", {public=true})
    add_files("../src/ols/src/extensions/*.cpp")

target("ols_ext_cgi")
    set_kind("static")
    add_deps("ols_base", "lsquic", "ols_log4cxx", "ols_http", "ols_ext")
    add_includedirs("../src/ols/src/extensions/cgi", {public=true})
    add_files("../src/ols/src/extensions/cgi/**.cpp|cgiconnection.cpp")
    add_files("../src/ols/src/extensions/cgi/*.c")

target("ols_ext_fcgi")
    set_kind("static")
    add_deps("ols_base", "lsquic", "ols_log4cxx", "ols_http", "ols_ext")
    add_includedirs("../src/ols/src/extensions/fcgi", {public=true})
    add_files("../src/ols/src/extensions/fcgi/**.cpp|sample*.cpp|fcgistarter.cpp|fcgirequest.cpp")

target("ols_ext_jk")
    set_kind("static")
    add_deps("ols_base", "lsquic", "ols_log4cxx", "ols_http", "ols_ext")
    add_includedirs("../src/ols/src/extensions/jk", {public=true})
    add_files("../src/ols/src/extensions/jk/**.cpp")

target("ols_ext_lsapi")
    set_kind("static")
    add_deps("ols_base", "lsquic", "ols_log4cxx", "ols_http", "ols_ext")
    add_includedirs("../src/ols/src/extensions/lsapi", {public=true})
    add_files("../src/ols/src/extensions/lsapi/**.cpp")

target("ols_ext_proxy")
    set_kind("static")
    add_deps("ols_base", "lsquic", "ols_log4cxx", "ols_http", "ols_ext")
    add_includedirs("../src/ols/src/extensions/proxy", {public=true})
    add_files("../src/ols/src/extensions/proxy/**.cpp")

target("ols_ext_registry")
    set_kind("static")
    add_deps("ols_base", "lsquic", "ols_log4cxx", "ols_http", "ols_ext")
    add_includedirs("../src/ols/src/extensions/registry", {public=true})
    add_files("../src/ols/src/extensions/registry/**.cpp")

target("ols_mod_modsec")
    set_kind("shared")
    add_deps("ols_base")
    add_includedirs("../src/mod_sec/headers")
    add_files("../src/mod_sec/src/.libs/libmodsecurity.a")
    add_files("../src/ols/src/modules/modsecurity-ls/*.cpp")

target("ols_mod_cache")
    set_kind("static")
    set_basename("mod_cache")
    add_deps("ols_base", "lsquic")
    add_includedirs("../src/ols/src/modules/cache")
    add_files("../src/ols/src/modules/cache/*.cpp")

target("ols_mod_cache")
    set_kind("shared")
    set_basename("mod_cache")
    add_deps("ols_base", "lsquic")
    add_includedirs("../src/ols/src/modules/cache")
    add_files("../src/ols/src/modules/cache/*.cpp")

target("ols_mod_js")
	set_kind("shared")
    add_deps("ols_base")
    add_includedirs("../src/ols/src/modules/js")
    add_files("../src/ols/src/modules/js/*.cpp")

target("ols_mod")
    set_kind("static")
    add_deps("ols_base", "ols_lsr", "ols_mod_gzip", "ols_mod_cache")
    add_files("../src/ols/src/modules/*.cpp")

-- target("ols_mod_lsrecaptcha")
-- 	set_kind("binary")
--     add_includedirs("../src/ols/src/modules/lsrecaptcha/src/ls/lsapi")
--     add_files("../src/ols/src/modules/lsrecaptcha/src/ls/lsapi/*.c")
--     add_files("../src/ols/src/modules/lsrecaptcha/src/ls/lsapi/*.go")
--     add_files("../src/ols/src/modules/lsrecaptcha/src/lsrecaptcha/*.go")
--     add_defines("CGO_ENABLED=1")
--     before_build(function(target)
--         print(os.getenv("CGO_ENABLED"))
--     end)

target("ols_mod_lua")
    set_kind("shared")
    add_deps("ols_base")
    add_packages("luajit")
    add_includedirs("../src/ols/src/modules/lua")
    add_files("../src/ols/src/modules/lua/*.cpp")

target("ols_mod_gzip")
    set_kind("static")
    add_deps("ols_base")
    add_packages("luajit", "zlib")
    add_includedirs("../src/ols/src/modules/modgzip")
    add_files("../src/ols/src/modules/modgzip/*.cpp")

target("ols_mod_inspector")
    set_kind("shared")
    add_deps("ols_base")
    add_packages("luajit")
    add_includedirs("../src/ols/src/modules/modinspector")
    add_files("../src/ols/src/modules/modinspector/*.cpp")

target("ols_mod_inspector")
    set_kind("shared")
    add_deps("ols_base")
    add_packages("luajit")
    add_includedirs("../src/ols/src/modules/modinspector")
    add_files("../src/ols/src/modules/modinspector/*.cpp")

target("ols_main")
    set_kind("static")
    add_deps("ols_base", "ols_lsr", "ols_util", "ols_sslpp")
    add_deps("lsquic", "maxminddb")
    add_packages("brotli", "luajit", "expat")
    add_includedirs("../src/ols/src/main")
    add_files("../src/ols/src/main/*.cpp")
    add_files("../src/boringssl/build/ssl/libssl.a")
    add_files("../src/boringssl/build/crypto/libcrypto.a")
    add_files("../src/boringssl/build/decrepit/libdecrepit.a")

target("openlitespeed")
    set_kind("binary")
    add_deps("lsquic", "maxminddb")
    add_packages("brotli", "luajit", "expat")
    add_deps("ols_base", "ols_lsr", "ols_util", "ols_edio", "ols_adns")
    add_deps("ols_h2", "ols_http", "ols_log4cxx", "ols_lsapi", "ols_quic")
    add_deps("ols_shm", "ols_socket", "ols_spdy", "ols_ssi", "ols_sslpp")
    add_deps("ols_thread", "ols_ext_cgi", "ols_ext_fcgi", "ols_ext_jk")
    add_deps("ols_ext_lsapi", "ols_ext_proxy", "ols_ext_registry", "ols_ext")
    add_deps("ols_mod_cache")
    add_deps("ols_main")
    add_files("../src/ols/src/main.cpp")
    add_files("../src/boringssl/build/ssl/libssl.a")
    add_files("../src/boringssl/build/crypto/libcrypto.a")
    add_files("../src/boringssl/build/decrepit/libdecrepit.a")
    add_ldflags("-pthread")